eval:
  goal_pose: [1, 0, 0, 0, 0.0, 0.2, 0.6]
  start_pose: [1, 0, 0, 0, 0.0, 0.0, 0.15]

setup:
  fixed_cube: true

sampler:
  visualize: true
  verbose: false

  augment: true
  n_rand_augmentations: 10
  augment_max_translation: 0.2
  augment_max_rotation: 0.5

  contact_modes: 
    X_POS: [[0.15, 0, 0], [-0.15, 0, 0]]
    X_NEG: [[-0.15, 0, 0], [0.15, 0, 0]]
    Y_POS: [[0, 0.15, 0], [0, -0.15, 0]]
    Y_NEG: [[0, -0.15, 0], [0, 0.15, 0]]
    # Z_POS: [[0, 0, 0.15], [0, 0, -0.15]]
    # Z_NEG: [[0, 0, -0.15], [0, 0, 0.15]]

  tabletop_configurations:
    n_rotations: 5 # Number of rotations per side. n_samples = n_rotations * 6

  box_height: 0.15

  primitives: ['YAW_90_cw', 'YAW_90_ccw', 'ROLL_90_cw', 'ROLL_90_ccw'] # ['YAW_90_cw', 'YAW_90_ccw', 'ROLL_90_cw', 'ROLL_90_ccw', 'PITCH_90_cw', 'PITCH_90_ccw', 'TO_GOAL']

  lift_height: 0.3
  num_steps: 25
  num_steps_lift: 12
  num_steps_rotate: 15
  num_steps_lower: 12